### ISSUE TITLE
Mapping Dossier PVA Course Development

### ISSUE THREAD

**Issue by CmdrKerfy** [ICPI/GIS#97]
## Development Timeline

Will update list with dates as appropriate 

### **Phase 1:**
- [ ] Planning meeting  [Everyone]
- [ ] Initial structure overview highlighting sections and key points  [@NateHeard]
   - [ ] Assign sections to  [@CmdrKerfy @SpaceForceOne ]

### **Phase 2:**
- [ ] Create first version of script  [Everyone]
- [ ] Second planning meeting to discuss script  [Everyone]
- [ ] Finalize script  [Everyone]

### **Phase 3:**
- [ ] Record sessions  [TBD]
- [ ] Review Recordings  [Everyone]
- [ ] Handover to PVA Team [@SpaceForceOne ]
